### ISSUE TITLE
Indigo Desktop has regressed on armhf due to an injected gazebo dependency

### ISSUE THREAD

**Issue by tfoote** [ros/metapackages#13]
urdf_tutorials now depends on gazebo_ros which depends on gazebo which is not available on indigo armhf. And the simulator is not supposed to be part of desktop. 

@sloretz Is this related to the urdf repo restructuring?

@ros/ros_team FYI

**Comment by mikaelarguedas** [comment]
@tfoote this is due to the last release of urdf_tutorial and not related to the robot_model repo split . @wjwwood opened https://github.com/ros/urdf_tutorial/issues/24 to track this.

**Comment by mikaelarguedas** [comment]
the suggested fix is to now put `urdf_tutorial` in `desktop-full` rather than in `desktop` so that we don't pull in new dependencies in `desktop`
