### ISSUE TITLE
[question] Updating docker images after each release?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/metapackages#16]
I noticed that the ROS docker images on DockerHub are outdated. Should we make it a best practice that every new release of this repository be followed by regenerating the dockerfiles in https://github.com/osrf/docker_images
@ros/ros_team thoughts?

**Comment by dirk-thomas** [comment]
Someone should be in charge of that repository and maintain up-to-date docker images. E.g. using automated builds - but that should be the choice of the maintainer.

**Comment by dirk-thomas** [comment]
I don't see how this is related to this repo. Should the ticket be created on the `osrf/docker_images` repo instead?

**Comment by mikaelarguedas** [comment]
We create docker images only for packages in this repo so I think this is tightly coupled. If there are different maintainers, the maintainer of `osrf/docker_images` would need to monitor the metapackages repo to know when an update of the dockerfiles is necessary. That doesn't seem optimal to me.

**Comment by dirk-thomas** [comment]
While I am the maintainer of the metapackages I won't be able to maintain the docker images. I see it as a responsibility of the person which created those to also keep them up-to-date.

The same goes for the Gazebo and SROS docker images. I wouldn't expect the Gazebo team to take over maintaining the Docker image.

**Comment by mikaelarguedas** [comment]
Conclusion on this: the ROS Boss of a given ROS release will be maintainer the docker images related to this release. Including making sure that they build and update them when a sync including a new metapackage version occurs.
