### ISSUE TITLE
"robot" variant depends on deprecated driver_common

### ISSUE THREAD

**Issue by mikeferguson** [ros/metapackages#3]
Noticed this during an audit of our package install. Should probably be removed for Indigo.

**Comment by dirk-thomas** [comment]
Thanks for the ticket. We will consider it when we create the indigo metapackages.

**Comment by dirk-thomas** [comment]
Done in https://github.com/ros/metapackages/commit/a64748022c63c3ae5cc27e78001e95445c96e2af#diff-4
