### ISSUE TITLE
desktop_full does not include rqt_plot

### ISSUE THREAD

**Issue by trainman419** [ros/metapackages#4]
As reported on ROS Answers: http://answers.ros.org/question/172663/ros-indigo-where-is-rqt_plot/?answer=172675#post-id-172675

It looks like the `desktop_full` variant doesn't include `rqt_plot`, probably because the `viz` variant doesn't include `rqt_common_plugins`

**Comment by wjwwood** [comment]
Hmm, we must have missed that when we refactored the metapackages. `rqt_common_plugins` should definitely be in there, thanks for the heads up.

We will need to make sure the REP is also up-to-date.

**Comment by dirk-thomas** [comment]
Part of it comes from https://github.com/ros-infrastructure/rep/commit/ecf1b4a5391bd00da993418b9448cbf6e8cbf084#diff-99357921d703ab390a3ff1a3540c61b3
